version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
environment:
  GitHubToken:
    secure: r6jryFbtdcnJ58qhoZOaNWcQWgueWcT9oSPAeX+vmoTC/yTiXCkhaYMhB9RuZbKD
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
deploy:
- provider: GitHub
  tag: 
  description: Vigilant Cupcake Releases
  auth_token:
    secure: r6jryFbtdcnJ58qhoZOaNWcQWgueWcT9oSPAeX+vmoTC/yTiXCkhaYMhB9RuZbKD
  on:
    branch: master
    appveyor_repo_tag: true
artifacts:
  - path: 'Releases\*'
    name: releases