version: '{branch}+{build}'
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{branch}'
  assembly_file_version: '{branch}'
  assembly_informational_version: '{branch}'
environment:
  GitHubToken:
    secure: r6jryFbtdcnJ58qhoZOaNWcQWgueWcT9oSPAeX+vmoTC/yTiXCkhaYMhB9RuZbKD
before_build:
- cmd: nuget restore
after_build:
- ps: ./squirrel.ps1
artifacts:
- path: Releases\*
  name: releases
deploy:
- provider: GitHub
  tag: 
  description: Vigilant Cupcake release
  auth_token:
    secure: r6jryFbtdcnJ58qhoZOaNWcQWgueWcT9oSPAeX+vmoTC/yTiXCkhaYMhB9RuZbKD
  on:
    branch: /v?\d+\.\d+\.\d+/
    appveyor_repo_tag: true