version: '{branch}+{build}'
os: Visual Studio 2015
configuration: Release
environment:
  GitHubToken:
    secure: r6jryFbtdcnJ58qhoZOaNWcQWgueWcT9oSPAeX+vmoTC/yTiXCkhaYMhB9RuZbKD
install:
- ps: >-
    $githubrelease = Invoke-RestMethod -Uri https://api.github.com/repos/amweiss/vigilant-cupcake/releases/latest?access_token=$env:GitHubToken | Select-Object -expand tag_name

    $env:LAST_RELEASE = $githubrelease.TrimStart('v')
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(LAST_RELEASE)'
  assembly_file_version: '$(LAST_RELEASE)'
  assembly_informational_version: '$(LAST_RELEASE)'
before_build:
- cmd: nuget restore
after_build:
- ps: ./squirrel.ps1
artifacts:
- path: Releases\*
  name: releases
deploy:
- provider: GitHub
  tag: 
  description: Vigilant Cupcake release
  auth_token:
    secure: r6jryFbtdcnJ58qhoZOaNWcQWgueWcT9oSPAeX+vmoTC/yTiXCkhaYMhB9RuZbKD
  on:
    branch: /v?\d+\.\d+\.\d+/
    appveyor_repo_tag: true