version: 1.1.{build}
os: Visual Studio 2015
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  GitHubToken:
    secure: r6jryFbtdcnJ58qhoZOaNWcQWgueWcT9oSPAeX+vmoTC/yTiXCkhaYMhB9RuZbKD
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- cmd: nuget restore
before_deploy:
- ps: $env:APPVEYOR_BUILD_FOLDER\squirrel.ps1
deploy:
- provider: GitHub
  tag: 
  description: Vigilant Cupcake Test
  auth_token:
    secure: r6jryFbtdcnJ58qhoZOaNWcQWgueWcT9oSPAeX+vmoTC/yTiXCkhaYMhB9RuZbKD
  on:
    branch: master
    appveyor_repo_tag: true
artifacts:
  - path: 'Releases\*'
    name: releases